//register
export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
//login
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
//logout
export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
//user
export const SET_USER = "SET_USER"
//peluquerias
export const GET_PELUQUERIAS = 'GET_PELUQUERIAS';
export const GET_PELUQUERIA_BY_ID = 'GET_PELUQUERIA_BY_ID';


export const LOGIN_GOOGLE = "LOGIN_GOOGLE";
export const LOGIN_GOOGLE_SUCCESS = "LOGIN_GOOGLE_SUCCESS";
export const LOGIN_GOOGLE_FAIL = "LOGIN_GOOGLE_FAIL";

export const LOGIN_ADMIN = "LOGIN_ADMIN";
export const LOGIN_ADMIN_SUCCESS = "LOGIN_ADMIN_SUCCESS";
export const LOGIN_ADMIN_FAIL = "LOGIN_ADMIN_FAIL";

export const REGISTER_ADMIN = "REGISTER_ADMIN_USER";
export const REGISTER_ADMIN_SUCCESS = "REGISTER_ADMIN_SUCCESS";
export const REGISTER_ADMIN_FAIL = "REGISTER_ADMIN_FAIL";
//filtros
export const FILTER_SERVICIES = 'FILTER_SERVICIES';
export const FILTER_RATING = 'FILTER_RATING';
export const FILTER_CALENDAR= 'FILTER_CALENDAR';
//search name
export const SEARCH_NAME = 'SEARCH_NAME'
export const SEARCH_CITY= 'SEARCH_CITY' 

export const LOGIN_GOOGLE_ADMIN = "LOGIN_GOOGLE_ADMIN";
export const LOGIN_GOOGLE_ADMIN_SUCCESS = "LOGIN_GOOGLE_ADMIN_SUCCESS";
export const LOGIN_GOOGLE_ADMIN_FAIL = "LOGIN_GOOGLE_ADMIN_FAIL";

export const POST_PELUQUERIA = 'POST_PELUQUERIA'

export const POST_FAVORITE = 'POST_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';